// ui/src/views/home/Home.vue
<template>
  <div class="Home">
    <h2>{{ sillyName }}</h2>
    <button class="btn pink-button" @click="JoinLobby">
      Join Game
    </button>
  </div>
</template>

<script>
import { getRandomItem, sillyWords } from "@/models/SillyWords";

export default {
  data: function() {
    return {
      sillyName: "Happy Fish Card Game"
    };
  },
  methods: {
    async JoinLobby() {
      await this.$router.push("JoinLobby");
    }
  },
  mounted() {
    // eslint-disable-next-line
    this.sillyName = `${getRandomItem(sillyWords.adjectives)} ${getRandomItem(sillyWords.nouns)} ${getRandomItem(sillyWords.adjectives)} Game`;
  }
};
</script>

<style>
.Home {
  text-align: center;
  color: #2c3e50;
}
</style>

// rewrite/frontend/src/views/Home.tsx
import  { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { sillyGameName } from '../util/sillyWords';

function Home() {
  const navigate = useNavigate();
  const [sillyName, setSillyName] = useState('Happy Fish Card Game');

  useEffect(() => {
    setSillyName(sillyGameName());
  }, []);

  return (
    <div className="Home">
      <h2>{sillyName}</h2>
      <button
        className="btn pink-button"
        onClick={() => navigate('/create')}
        style={{ marginTop: '20px' }}
      >
        Create a New Game
      </button>
      <button
        className="btn pink-button"
        onClick={() => navigate('/join')}
        style={{ marginTop: '20px' }}
      >
        Join a Game
      </button>
    </div>
  );
}

export default Home;
