// rewrite/frontend/src/views/Home.tsx
import  { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { sillyGameName } from '../util/sillyWords';

function Home() {
  const navigate = useNavigate();
  const [sillyName, setSillyName] = useState('Happy Fish Card Game');

  useEffect(() => {
    setSillyName(sillyGameName());
  }, []);

  return (
    <div className="Home">
      <h2>{sillyName}</h2>
      <button
        className="btn pink-button"
        onClick={() => navigate('/create')}
        style={{ marginTop: '20px' }}
      >
        Create a New Game
      </button>
      <button
        className="btn pink-button"
        onClick={() => navigate('/join')}
        style={{ marginTop: '20px' }}
      >
        Join a Game
      </button>
    </div>
  );
}

export default Home;

// ui/src/views/Home.vue
<template>
  <div class="Home">
    <h2>Happy Fish Card Game</h2>
    <button class="btn btn-secondary" @click="JoinLobby">
      Join Game
    </button>
    <p>
      The host of the game should go <router-link to="/Host">here</router-link>
    </p>
  </div>
</template>

<script>

export default {
  methods: {
    async JoinLobby() {
      await this.$router.push("JoinLobby");
    }
  }
};
</script>

<style>
.Home {
  text-align: center;
  color: #2c3e50;
}

</style>
